<a href="https://colab.research.google.com/github/vaseem-20/Artificial-Intelligence/blob/main/ANN_model_building_Reggretion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('/content/Folds5x2_pp.csv')
df

AT      V       AP     RH      PE
0      8.34  40.77  1010.84  90.01  480.48
1     23.64  58.49  1011.40  74.20  445.75
2     29.74  56.90  1007.15  41.91  438.76
3     19.07  49.69  1007.22  76.79  453.09
4     11.80  40.66  1017.13  97.20  464.43
...     ...    ...      ...    ...     ...
9563  15.12  48.92  1011.80  72.93  462.59
9564  33.41  77.95  1010.30  59.72  432.90
9565  15.99  43.34  1014.20  78.66  465.96
9566  17.65  59.87  1018.58  94.65  450.93
9567  23.68  51.30  1011.86  71.24  451.67

[9568 rows x 5 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [7]:
df.describe()

AT            V           AP           RH           PE
count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.365009
std       7.452473    12.707893     5.938784    14.600269    17.066995
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.750000
50%      20.345000    52.080000  1012.940000    74.975000   451.550000
75%      25.720000    66.540000  1017.260000    84.830000   468.430000
max      37.110000    81.560000  1033.300000   100.160000   495.760000

In [8]:
df.columns

Index(['AT', 'V', 'AP', 'RH', 'PE'], dtype='object')

In [12]:
df.rename(columns={'AT':'average_temparature',
                   'V':'exhuast_vaccume',
                   'AP':'Ambident_pressure',
                   'RH':'relative_humidity',
                   'PE':'ee_consumption'},inplace=True)

In [13]:
df

average_temparature  exhuast_vaccume  Ambident_pressure  \
0                    8.34            40.77            1010.84   
1                   23.64            58.49            1011.40   
2                   29.74            56.90            1007.15   
3                   19.07            49.69            1007.22   
4                   11.80            40.66            1017.13   
...                   ...              ...                ...   
9563                15.12            48.92            1011.80   
9564                33.41            77.95            1010.30   
9565                15.99            43.34            1014.20   
9566                17.65            59.87            1018.58   
9567                23.68            51.30            1011.86   

      relative_humidity  ee_consumption  
0                 90.01          480.48  
1                 74.20          445.75  
2                 41.91          438.76  
3                 76.79          453.09  
4                 97.20          464.43  
...                 ...             ...  
9563              72.93          462.59  
9564              59.72          432.90  
9565              78.66          465.96  
9566              94.65          450.93  
9567              71.24          451.67  

[9568 rows x 5 columns]

In [14]:
df.head()

average_temparature  exhuast_vaccume  Ambident_pressure  relative_humidity  \
0                 8.34            40.77            1010.84              90.01   
1                23.64            58.49            1011.40              74.20   
2                29.74            56.90            1007.15              41.91   
3                19.07            49.69            1007.22              76.79   
4                11.80            40.66            1017.13              97.20   

   ee_consumption  
0          480.48  
1          445.75  
2          438.76  
3          453.09  
4          464.43

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   average_temparature  9568 non-null   float64
 1   exhuast_vaccume      9568 non-null   float64
 2   Ambident_pressure    9568 non-null   float64
 3   relative_humidity    9568 non-null   float64
 4   ee_consumption       9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [16]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   average_temparature  9568 non-null   float64
 1   exhuast_vaccume      9568 non-null   float64
 2   Ambident_pressure    9568 non-null   float64
 3   relative_humidity    9568 non-null   float64
 4   ee_consumption       9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [17]:
df.corr()

average_temparature  exhuast_vaccume  Ambident_pressure  \
average_temparature             1.000000         0.844107          -0.507549   
exhuast_vaccume                 0.844107         1.000000          -0.413502   
Ambident_pressure              -0.507549        -0.413502           1.000000   
relative_humidity              -0.542535        -0.312187           0.099574   
ee_consumption                 -0.948128        -0.869780           0.518429   

                     relative_humidity  ee_consumption  
average_temparature          -0.542535       -0.948128  
exhuast_vaccume              -0.312187       -0.869780  
Ambident_pressure             0.099574        0.518429  
relative_humidity             1.000000        0.389794  
ee_consumption                0.389794        1.000000

In [ ]:
# split the data

In [25]:
x=df.drop('ee_consumption',axis=1).values
y=df['ee_consumption'].values

In [27]:
x

array([[   8.34,   40.77, 1010.84,   90.01],
       [  23.64,   58.49, 1011.4 ,   74.2 ],
       [  29.74,   56.9 , 1007.15,   41.91],
       ...,
       [  15.99,   43.34, 1014.2 ,   78.66],
       [  17.65,   59.87, 1018.58,   94.65],
       [  23.68,   51.3 , 1011.86,   71.24]])

In [26]:
y

array([480.48, 445.75, 438.76, ..., 465.96, 450.93, 451.67])

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [39]:
x_test

array([[  27.4 ,   69.13, 1001.4 ,   82.47],
       [  21.94,   57.5 , 1014.64,   78.52],
       [  25.87,   57.32, 1012.06,   44.13],
       ...,
       [  20.64,   49.21, 1014.86,   58.47],
       [  23.28,   60.84, 1017.91,   67.5 ],
       [  28.7 ,   71.64, 1007.11,   69.85]])

In [40]:
y_train

array([461.6 , 435.66, 451.29, ..., 437.88, 449.91, 473.76])

In [44]:
from sklearn.preprocessing import StandardScaler

In [46]:
scaler=StandardScaler()
scaler

StandardScaler()

In [47]:
x_train_scale=scaler.fit_transform(x_train)

In [49]:
x_test_scaler=scaler.transform(x_test)
x_test_scaler

array([[ 1.04271077,  1.1677481 , -2.00565355,  0.61698162],
       [ 0.30987852,  0.25321117,  0.2377912 ,  0.34699369],
       [ 0.83735668,  0.23905669, -0.19937552, -2.00361006],
       ...,
       [ 0.13539466, -0.39868144,  0.27506898, -1.02345136],
       [ 0.48973112,  0.51585549,  0.79187461, -0.40623845],
       [ 1.21719463,  1.36512452, -1.03812564, -0.24561272]])

In [53]:
x_train.shape

(7654, 4)

In [ ]:
# model architecture

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [54]:
import tensorflow as tf

In [52]:
model=Sequential()
model

<Sequential name=sequential_1, built=False>

In [56]:
model.add(tf.keras.layers.Input(shape=[4],name='input_layer'))
model.add(Dense(units=64,activation='relu',name='hidden_layer_1'))
model.add(Dense(units=32,activation='relu',name='hidden_layer_2'))
model.add(Dense(units=16,activation='relu',name='hidden_layer_3'))
model.add(Dense(units=1,name='output_layer'))

In [60]:
from tensorflow.keras.callbacks import EarlyStopping

In [62]:
model.compile(
    optimizer='adam',
    loss='mean_squared_error',

  )

In [63]:
model.fit(
    x=x_train_scale,
    y=y_train,
    epochs=100,
    batch_size=32,
    validation_data=(x_test_scaler,y_test),
    callbacks=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)
)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 20.0530 - mae: 3.4153 - val_loss: 23.4063 - val_mae: 3.7748
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 19.4844 - mae: 3.4116 - val_loss: 24.5402 - val_mae: 3.9118
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 18.4484 - mae: 3.3044 - val_loss: 16.9080 - val_mae: 3.2793
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 19.6633 - mae: 3.3792 - val_loss: 20.2013 - val_mae: 3.6069
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 18.0728 - mae: 3.2509 - val_loss: 19.4274 - val_mae: 3.5339
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 18.3434 - mae: 3.3119 - val_loss: 17.8303 - val_mae: 3.2961
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 17.9046 - mae: 3.2883 - val_loss: 16.7631 - val_mae: 3.2773
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.0784 - mae: 3.3435 - val_loss: 16.8335 - val_mae: 3.2413
Epoch 9/100
240/240 ━━━━━━━━━━━━

In [64]:
pd.DataFrame(model.history.history)

loss       mae   val_loss   val_mae
0   18.857157  3.334384  23.406326  3.774818
1   19.417389  3.385133  24.540236  3.911825
2   18.458881  3.304323  16.908012  3.279331
3   18.835701  3.330729  20.201309  3.606895
4   18.670732  3.321757  19.427443  3.533921
5   18.545250  3.305265  17.830330  3.296140
6   18.458357  3.303658  16.763123  3.277285
7   19.680279  3.419878  16.833511  3.241339
8   18.685028  3.331832  17.308489  3.279336
9   18.797087  3.344109  16.604137  3.234627
10  19.165548  3.364679  19.968510  3.573718
11  19.549688  3.403805  19.870115  3.481786
12  18.499372  3.306086  17.532240  3.303861
13  18.535994  3.299712  23.463085  3.734321
14  18.818493  3.336826  19.285151  3.398810
15  19.417137  3.382651  27.552338  4.263439
16  18.753847  3.334862  19.904493  3.612338
17  19.233734  3.366886  17.655771  3.374097
18  19.058708  3.367578  17.815090  3.349471
19  19.005322  3.354316  25.296450  4.006946

In [65]:
model.evaluate(x_test_scaler,y_test)

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15.6824 - mae: 3.1355


[16.604137420654297, 3.2346272468566895]

In [66]:
model.evaluate(x_train_scale,y_train)

240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.0317 - mae: 3.1280


[16.88461685180664, 3.144904851913452]

In [68]:
prediction = model.predict(x_test_scaler)
prediction

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[430.99768],
       [448.37436],
       [445.64923],
       ...,
       [456.11865],
       [447.1177 ],
       [433.16672]], dtype=float32)

In [69]:
prediction_df=pd.DataFrame(np.ravel(prediction),columns=['prediction'])
prediction_df

prediction
0     430.997681
1     448.374359
2     445.649231
3     446.367554
4     461.894745
...          ...
1909  468.075623
1910  433.067383
1911  456.118652
1912  447.117706
1913  433.166718

[1914 rows x 1 columns]

In [70]:
compare_df=pd.concat([pd.DataFrame(y_test,columns=['true_values']),prediction_df],axis=1)
compare_df

true_values  prediction
0          426.18  430.997681
1          451.10  448.374359
2          442.87  445.649231
3          443.70  446.367554
4          460.59  461.894745
...           ...         ...
1909       468.19  468.075623
1910       431.16  433.067383
1911       454.20  456.118652
1912       444.13  447.117706
1913       436.58  433.166718

[1914 rows x 2 columns]

In [73]:
from sklearn import metrics

In [74]:
metrics.mean_absolute_error(y_test,prediction)

3.2346280503547047

In [75]:
metrics.mean_squared_error(y_test,prediction)


16.604141330524328

In [77]:
print('rmse:',np.sqrt(metrics.mean_squared_error(y_test,prediction)))

rmse: 4.07481795059906
