<a href="https://colab.research.google.com/github/vaseem-20/Artificial-Intelligence/blob/main/KNN_algorithum_Regression_model_building.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,RandomizedSearchCV
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor,KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error,confusion_matrix,roc_auc_score,roc_curve,accuracy_score,precision_score,recall_score,f1_score,precision_recall_curve

In [2]:
wine = load_wine()

In [3]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [4]:
wine.target_names


array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [5]:
x_cls = wine.data
x_cls


array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [6]:
y_cls=wine.target
y_cls

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [7]:
#standardizing features
scaler_cls = StandardScaler()
x_cls_scaled = scaler_cls.fit_transform(x_cls)
x_cls_scaled

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x_cls_scaled,y_cls,test_size=0.2,random_state=20,stratify=y_cls)

In [9]:
#KNN Classification (Without Regularization)


In [11]:
knn_cls_no_reg=KNeighborsClassifier(n_neighbors=5,weights='uniform')
knn_cls_no_reg.fit(x_train,y_train)
knn_cls_no_reg


KNeighborsClassifier()

In [13]:
y_cls_pred_no_reg=knn_cls_no_reg.predict(x_test)
y_cls_pred_no_reg

array([0, 2, 0, 2, 0, 1, 0, 0, 1, 1, 2, 1, 2, 2, 2, 0, 1, 0, 1, 1, 1, 0,
       0, 2, 0, 0, 2, 0, 1, 0, 1, 1, 2, 0, 1, 2])

In [14]:
#classification metric
print(classification_report(y_test,y_cls_pred_no_reg))
print('KNN Classification (without Regulation)')
print('accuracy:',accuracy_score(y_test,y_cls_pred_no_reg))
print('precision:',precision_score(y_test,y_cls_pred_no_reg,average='weighted'))
print('recall:',recall_score(y_test,y_cls_pred_no_reg,average='weighted'))
print('f1_score:',f1_score(y_test,y_cls_pred_no_reg,average='weighted'))

              precision    recall  f1-score   support

           0       0.86      1.00      0.92        12
           1       1.00      0.86      0.92        14
           2       1.00      1.00      1.00        10

    accuracy                           0.94        36
   macro avg       0.95      0.95      0.95        36
weighted avg       0.95      0.94      0.94        36

KNN Classification (without Regulation)
accuracy: 0.9444444444444444
precision: 0.9523809523809523
recall: 0.9444444444444444
f1_score: 0.9444444444444444


In [17]:
#KNN classification with regulation

knn_cls_reg=KNeighborsClassifier(n_neighbors=5,weights='distance')
knn_cls_reg.fit(x_train,y_train)
knn_cls_reg

KNeighborsClassifier(weights='distance')

In [18]:
y_cls_pred_reg=knn_cls_no_reg.predict(x_test)
y_cls_pred_reg

array([0, 2, 0, 2, 0, 1, 0, 0, 1, 1, 2, 1, 2, 2, 2, 0, 1, 0, 1, 1, 1, 0,
       0, 2, 0, 0, 2, 0, 1, 0, 1, 1, 2, 0, 1, 2])

In [19]:

print(classification_report(y_test,y_cls_pred_reg))
print('KNN Classification (without Regulation - weighted Distance)')
print('accuracy:',accuracy_score(y_test,y_cls_pred_reg))
print('precision:',precision_score(y_test,y_cls_pred_reg,average='weighted'))
print('recall:',recall_score(y_test,y_cls_pred_reg,average='weighted'))
print('f1_score:',f1_score(y_test,y_cls_pred_reg,average='weighted'))

              precision    recall  f1-score   support

           0       0.86      1.00      0.92        12
           1       1.00      0.86      0.92        14
           2       1.00      1.00      1.00        10

    accuracy                           0.94        36
   macro avg       0.95      0.95      0.95        36
weighted avg       0.95      0.94      0.94        36

KNN Classification (without Regulation - weighted Distance)
accuracy: 0.9444444444444444
precision: 0.9523809523809523
recall: 0.9444444444444444
f1_score: 0.9444444444444444


In [33]:
param_grid_cls={
    'n_neighbors':np.arange(1,20),
    'weights':['uniform','distance'],
    'metric':['euclidean','manhattan','minkowski']
}

In [ ]:
#KNN Classification (Hyperparameter tuning)

In [34]:
knn_cls_tuned=RandomizedSearchCV(KNeighborsClassifier(),param_grid_cls,n_iter=10,cv=5,random_state=42)
knn_cls_tuned.fit(x_train,y_train)
knn_cls_tuned

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(),
                   param_distributions={'metric': ['euclidean', 'manhattan',
                                                   'minkowski'],
                                        'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19]),
                                        'weights': ['uniform', 'distance']},
                   random_state=42)

In [35]:
print('Best param KNN Classification',knn_cls_tuned.best_params_)
y_cls_pred_tuned=knn_cls_tuned.predict(x_test)
y_cls_pred_tuned

Best param KNN Classification {'weights': 'distance', 'n_neighbors': np.int64(16), 'metric': 'manhattan'}


array([0, 2, 0, 2, 0, 1, 0, 0, 1, 1, 2, 1, 2, 2, 2, 0, 1, 0, 1, 1, 1, 0,
       0, 2, 0, 0, 2, 0, 1, 0, 1, 1, 2, 0, 0, 2])

In [36]:
print(classification_report(y_test,y_cls_pred_tuned))
print('KNN Classification (without Regulation - weighted Distance)')
print('accuracy:',accuracy_score(y_test,y_cls_pred_tuned))
print('precision:',precision_score(y_test,y_cls_pred_tuned,average='weighted'))
print('recall:',recall_score(y_test,y_cls_pred_tuned,average='weighted'))
print('f1_score:',f1_score(y_test,y_cls_pred_tuned,average='weighted'))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89        12
           1       1.00      0.79      0.88        14
           2       1.00      1.00      1.00        10

    accuracy                           0.92        36
   macro avg       0.93      0.93      0.92        36
weighted avg       0.93      0.92      0.92        36

KNN Classification (without Regulation - weighted Distance)
accuracy: 0.9166666666666666
precision: 0.9333333333333333
recall: 0.9166666666666666
f1_score: 0.9162962962962963


In [38]:
print('mse:',mean_squared_error(y_test,y_cls_pred_tuned))
print('r2:',r2_score(y_test,y_cls_pred_tuned))
print('mae:',mean_absolute_error(y_test,y_cls_pred_tuned))
print('rmse:',np.sqrt(mean_squared_error(y_test,y_cls_pred_tuned)))

mse: 0.08333333333333333
r2: 0.8629441624365481
mae: 0.08333333333333333
rmse: 0.28867513459481287
